### PR TITLE
fixes #379, reactivates GST and fixed 32 bit problem

### LINKED ISSUE #379: missing generalStateTest from CI
during march 19-20 features addition of `test_generalstate_json.nim`, I accidentally made GST disappeared from CI log. And because we are not aware of this situation, many new 32 bit GST failed during byzantium and constantinople implementation.

I already know whats wrong. but I open this issue to remind myself of related TODOs:
- [x] make GST appear in CI again
- [x] remove old 32 bit failed GST from skip list if it already fixed
- [x] include new 32 bit failed GST into skip list

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

File: nimbus/vm/transaction_tracer.nim [hunk 1]
```diff
@@ -104,7 +104,7 @@ proc traceOpCodeEnded*(tracer: var TransactionTracer, c: BaseComputation, op: Op
         storage[key.dumpHex] = %(value.dumpHex)
       j["storage"] = storage
 
-  let gasRemaining = j["gas"].getInt()
+  let gasRemaining = j["gas"].getBiggestInt()
```
Comment (arnetheduck) [inline nimbus/vm/transaction_tracer.nim]: aren't we simply going from one "random" int size to another here?

Comment (jangko) [reply nimbus/vm/transaction_tracer.nim]: well yeah, too bad std-lib json library doesn't offer better alternative.

Comment (zah) [reply nimbus/vm/transaction_tracer.nim]: As a long-term to-do item, you can try to define the Tracer json structures as a strongly-typed values in Nim and then rely on `nim-json-serialization` to save and load them. This will give you slightly more control over the data types.

Comment (jangko) [reply nimbus/vm/transaction_tracer.nim]: all-right, I will add it to #177 todo list
